# Generated by Django 6.0.4 on 2026-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('paused', 'Paused'), ('repeating', 'Repeating')], default='planning', max_length=16),
        ),
    ]
